version: '2'
services:
  postgres:
    image: postgres:13
    environment:
      - "POSTGRES_DB=ressam"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    command: [ "postgres", "-c", "log_statement=all" ]
  goose:
    image: gomicro/goose
    depends_on:
      - postgres
    volumes:
      - ./pg/testdata/migrations:/app/migrations
    expose:
      - "5432"
    restart: on-failure
    entrypoint: [ "goose", "-dir=/app/migrations", "postgres",
                  "postgresql://postgres:postgres@postgres:5432/ressam?sslmode=disable", "up" ]
